/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f1xx.h"
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
// Slave address (7-bit format, replace with the actual address of your slave device)
#define SLAVE_ADDR  0x27
#define BACKLIGHT_FLAG 0x08   // Backlight control bit
#define ENABLE_FLAG 0x04      // Enable pin control bit
#define RS_FLAG 0x01          // Register Select control bit
#define COMMAND_MODE 0x00     // RS = 0 (Command mode)
#define DATA_MODE RS_FLAG     // RS = 1 (Data mode)
#define ADS1115_ADDR 0x48

bool backlight = 0;

void GPIO_Init(void) {
    // Enable GPIO and AFIO clocks
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN |
                    RCC_APB2ENR_IOPBEN |
                    RCC_APB2ENR_IOPCEN |
                    RCC_APB2ENR_AFIOEN;

    // Reset ports
    RCC->APB2RSTR |= RCC_APB2RSTR_IOPARST | RCC_APB2RSTR_IOPBRST | RCC_APB2RSTR_IOPCRST;
    RCC->APB2RSTR &= ~(RCC_APB2RSTR_IOPARST | RCC_APB2RSTR_IOPBRST | RCC_APB2RSTR_IOPCRST);

    // Remap I2C1 to PB8/PB9
    AFIO->MAPR |= AFIO_MAPR_I2C1_REMAP;

    // Configure PB8 and PB9 as alternate function open-drain
    GPIOB->CRH &= ~((GPIO_CRH_MODE8 | GPIO_CRH_CNF8) |
                    (GPIO_CRH_MODE9 | GPIO_CRH_CNF9));
    GPIOB->CRH |= ((GPIO_CRH_MODE8_1) | (GPIO_CRH_CNF8_1 | GPIO_CRH_CNF8_0)) |
                  ((GPIO_CRH_MODE9_1) | (GPIO_CRH_CNF9_1 | GPIO_CRH_CNF9_0));

    // Optional: Enable internal pull-ups (for testing)
    GPIOB->ODR |= (1 << 8) | (1 << 9);
}


void system_clk()
{
	//ENABLE HSE AND WAIT TILL IT BECOMES READY
	RCC->CR |= RCC_CR_HSEON;	//HSE @8MHZ
	while(!(RCC->CR & RCC_CR_HSERDY))
		;

	//CONFIGURE FLASH PREFETCH AND LATENCY SETTINGS
	FLASH->ACR |= FLASH_ACR_PRFTBE|FLASH_ACR_LATENCY_1;

	//CONFIGURE PLL AND BUSES (AHB,APB1,APB2)
	//PLL SOURCE: HERE HSE IS USED AS A SOURCE
	RCC->CFGR |= RCC_CFGR_PLLSRC;
	//HSE DIVIDER FOR PLL (IF HSE IS USED AS SOURCE FOR PLL)
	RCC->CFGR |= RCC_CFGR_PLLXTPRE_HSE;	//INPUT TO PLL 8MHZ
	//PLL MULTIPLIER: HERE HSE OUTPUT IS MULTIPLIED WITH 4
	RCC->CFGR |= RCC_CFGR_PLLMULL4;	//OUTPUT TO PLL IS 32MHZ
	//BUS CLOCK CONFIGURE(APB1,APB2,AHB): NOT DIVIDING
	RCC->CFGR |= (RCC_CFGR_PPRE1_DIV1|RCC_CFGR_PPRE2_DIV1|RCC_CFGR_HPRE_DIV1);
	//ENABLE THE PLL
	RCC->CR |= RCC_CR_PLLON;
	//WAIT FOR PLL TO SET
	while(!(RCC->CR & RCC_CR_PLLRDY))
		;

	//ENABLE SYSTEMCLK AND WAIT
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS_PLL))
		;

	GPIO_Init();
	//CLOCK OUTPUT ON MCO PIN
	RCC->CFGR |= RCC_CFGR_MCO_SYSCLK;
}


/* Timer Frequency (TF) = bus Clock(Fsysclk)/(Prescaler(TIM2PSC) + 1)
 *
 * Timer tim Period (TTM) = 1/timer frequency(TF)
 *
 * Time delay by timer = Timer Time Period * Timer Auto Reload Register(TIM2ARR)
 *
 * System clock = 32MHz, TIM2PSC = 32, so TF = 1MHz
 *
 * TTP = 1us
 * TIM2AEE = 0xffff
 */


void delay_us(uint16_t us) {
    uint16_t start = TIM2->CNT; // Capture the current counter value
    while ((TIM2->CNT - start) < us); // Wait until the elapsed time matches 'us'
}


void delay_ms(uint16_t ms){
	for (uint16_t i=0; i<ms; i++)
		delay_us(1000);
}

void timer_init(){
	//Start by making sure that the timer's 'counter' is off
	TIM2->CR1 &= ~(TIM_CR1_CEN);
	TIM2->SR &= ~(TIM_SR_UIF);

	//RESET THE TIMER2 BUS
	RCC->APB1RSTR |= (RCC_APB1RSTR_TIM2RST);
	RCC->APB1RSTR &= ~(RCC_APB1RSTR_TIM2RST);

	//ENABLE THE TIMER2 PERIPHERAL CLOCK
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;


	/**********Eg1************/
	//Timer Prescaler value
	TIM2->PSC = 31;

	//Timer Auto Reload Register Value
	TIM2->ARR = 0xffff;

	//ENABLE THE UPDATE GENERATION
	TIM2->EGR |= TIM_EGR_UG;

	TIM2->CR1 |=TIM_CR1_CEN;
//	while(!(TIM2->SR & (1<<TIM_SR_UIF)));
}


void I2C1_Init(void) {
    // Enable I2C1 clock
    RCC->APB1ENR |= RCC_APB1ENR_I2C1EN;

    // Reset I2C1
    RCC->APB1RSTR |= RCC_APB1RSTR_I2C1RST;
    RCC->APB1RSTR &= ~RCC_APB1RSTR_I2C1RST;

    // Configure I2C_CR2 for peripheral input clock (FREQ = 36 MHz for STM32F103, this is the default)
    I2C1->CR2 = 32;
    I2C1->CCR = 160;
    I2C1->TRISE = 33;

    // Enable I2C peripheral
    I2C1->CR1 |= I2C_CR1_PE;
}

void I2C1_Writea(uint8_t addr, uint8_t data, uint8_t length) {
	// Wait until I2C is not busy
	    while (I2C1->SR2 & I2C_SR2_BUSY);

	    // Send start condition
	    I2C1->CR1 |= I2C_CR1_START;

	    // Wait for start bit generation
	    while (!(I2C1->SR1 & I2C_SR1_SB));

	    // Send slave address with write bit (addr << 1 | 0)
	    I2C1->DR = (addr << 1);

	    // Wait for address acknowledgment
	    while (!(I2C1->SR1 & I2C_SR1_ADDR));
	    (void)I2C1->SR2;  // Clear ADDR flag by reading SR2

	    // Send data
	    if (backlight == 1)
	    {
	    	data |= BACKLIGHT_FLAG;
	    }
	    I2C1->DR = data;

	    // Wait for byte transfer complete
	    while (!(I2C1->SR1 & I2C_SR1_BTF));

	    // Send stop condition
	    I2C1->CR1 |= I2C_CR1_STOP;
}

void I2C1_Write(uint8_t addr, uint8_t *data, uint8_t length) {
    // Wait until I2C is not busy
    while (I2C1->SR2 & I2C_SR2_BUSY);

    // Send start condition
    I2C1->CR1 |= I2C_CR1_START;

    // Wait for start condition
    while (!(I2C1->SR1 & I2C_SR1_SB));

    // Send slave address with write bit (addr << 1)
    I2C1->DR = (addr << 1);

    // Wait for address acknowledgement
    while (!(I2C1->SR1 & I2C_SR1_ADDR));
    (void)I2C1->SR2;  // Clear the ADDR flag by reading SR2

    // Send the data bytes
    for (uint8_t i = 0; i < length; i++) {
        I2C1->DR = data[i];
        while (!(I2C1->SR1 & I2C_SR1_BTF));  // Wait for byte transfer to finish
    }

    // Send stop condition
    I2C1->CR1 |= I2C_CR1_STOP;
}
void enableBacklight(){
	backlight = 1;
	I2C1_Writea(SLAVE_ADDR, BACKLIGHT_FLAG,1);
}

void setCursor(uint8_t column, uint8_t row){
	static const uint8_t ROW_OFFSETS[] = {0x00, 0x40, 0x14, 0x54};
	sendByteToLCD(0x80 | (column + ROW_OFFSETS[row]), COMMAND_MODE);
}

// Function to send an LCD command
void sendCommand(uint8_t command){
    sendByteToLCD(command, COMMAND_MODE);
}

void lcdInit(){
	delay_ms(50);
	send4BitData(0x30, COMMAND_MODE);  // Initialize to 8-bit mode
	delay_ms(5);
	send4BitData(0x30, COMMAND_MODE);  // Repeat initialization
	delay_ms(5);
	send4BitData(0x30, COMMAND_MODE);  // Ensure initialization
	delay_ms(5);
	send4BitData(0x20, COMMAND_MODE);  // Switch to 4-bit mode

	sendCommand(0x28);  // Function set: 4-bit mode, 2-line display, 5x8 dots
	sendCommand(0x0C);  // Display ON, cursor OFF
	sendCommand(0x06);  // Entry mode: Increment cursor, no shift
	sendCommand(0x01);  // Clear display
	delay_ms(2);           // Wait for clearing to complete

}

// Function to toggle the Enable pin to latch data
void pulseEnable(uint8_t data) {
    I2C1_Writea(SLAVE_ADDR, data | ENABLE_FLAG, 1);
    delay_us(1);
    I2C1_Writea(SLAVE_ADDR, data & ~ENABLE_FLAG, 1);
    delay_us(50);
}


// Function to send 4-bit data to the LCD
void send4BitData(uint8_t data, uint8_t mode){
	uint8_t control;
	if (backlight == 1)
	{
		control = mode | BACKLIGHT_FLAG;
	}
	else{
		control = mode;
	}
    I2C1_Writea(SLAVE_ADDR, data | control,1);  // Send data
    pulseEnable(data | control);
}

// Function to send a full byte of data to the LCD (split into high and low nibbles)
void sendByteToLCD(uint8_t byte, uint8_t mode){
    send4BitData(byte & 0xF0, mode);         // Send high nibble
    send4BitData((byte << 4) & 0xF0, mode);  // Send low nibble
}

// Function to send data (characters) to the LCD
void sendData(uint8_t data) {
    sendByteToLCD(data, DATA_MODE);
}

void LCDPrintString(char *string){
	for (int i = 0; string[i] != '\0'; i++) {
		sendData((uint8_t)string[i]);
	}
}

void LCD_SendCmd(uint8_t cmd) {
    send4BitData(cmd, COMMAND_MODE);
}

void LCD_SetCursor(uint8_t row, uint8_t col) {
    uint8_t address = (row == 0) ? 0x80 : 0xC0;  // 0x80 for row 0, 0xC0 for row 1
    address += col;  // Add the column offset
    send4BitData(address, COMMAND_MODE);
}

void I2C1_Scan(void) {
    char buf[16];
    uint8_t found = 0;

    sendCommand(0x01); // Clear LCD
    setCursor(0, 0);
    LCDPrintString("Scanning...");

    for (uint8_t addr = 1; addr < 127; addr++) {
        // Generate START
        I2C1->CR1 |= I2C_CR1_START;
        while (!(I2C1->SR1 & I2C_SR1_SB));

        // Send address
        I2C1->DR = (addr << 1);
        while (!(I2C1->SR1 & (I2C_SR1_ADDR | I2C_SR1_AF)));

        if (I2C1->SR1 & I2C_SR1_ADDR) {
            (void)I2C1->SR2; // clear ADDR
            I2C1->CR1 |= I2C_CR1_STOP;
            found++;

            sendCommand(0x01); // clear
            setCursor(0, 0);
            snprintf(buf, sizeof(buf), "Found: 0x%02X", addr);
            LCDPrintString(buf);
            delay_ms(1000);
        }

        I2C1->SR1 &= ~I2C_SR1_AF; // clear AF flag
        I2C1->CR1 |= I2C_CR1_STOP;
        delay_ms(10);
    }

    if (found == 0) {
        sendCommand(0x01);
        setCursor(0, 0);
        LCDPrintString("No device found");
    }
}


int main(void)
{
    system_clk();
    timer_init();
    I2C1_Init();
    enableBacklight();
    lcdInit();

    while (1) {
        I2C1_Scan();
        delay_ms(2000);
    }
}

